export const products = [
  {
    id: 1,
    title: "Remeron Abstract",
    price: 8500,
    stock: 5,
    description: "Oversize",
    category: "Remeron",
    img: "https://res.cloudinary.com/dfcnmxndf/image/upload/v1686949763/remeraAngelAdelante_p7wc01.png",
  },
  {
    id: 2,
    title: "Remeron Metal Gun",
    price: 8500,
    stock: 5,
    description: "Oversize",
    category: "remeron",
    img: "https://res.cloudinary.com/dfcnmxndf/image/upload/v1686949762/remeraArmando_dbsbqy.png",
  },
  {
    id: 3,
    title: "Remeron Revolution",
    price: 8500,
    stock: 5,
    description: "Oversize",
    category: "Remeron",
    img: "https://res.cloudinary.com/dfcnmxndf/image/upload/v1686949762/remeraArea51Atras_xg69c7.png",
  },
  {
    id: 4,
    title: "Remeron Full Dominion",
    price: 8500,
    stock: 5,
    description: "Oversize",
    category: "Remeron",
    img: "https://res.cloudinary.com/dfcnmxndf/image/upload/v1686949762/remeraAngelAtras_joeust.png",
  },
  {
    id: 5,
    title: "Remeron The Rose",
    price: 8500,
    stock: 5,
    description: "Oversize",
    category: "Remeron",
    img: "https://res.cloudinary.com/dfcnmxndf/image/upload/v1686949764/remeraBeisbol_daog0n.png",
  },
  {
    id: 6,
    title: "Buzo El Riqui",
    price: 16000,
    stock: 5,
    description: "Oversize",
    category: "Buzo",
    img: "https://res.cloudinary.com/dfcnmxndf/image/upload/v1686949761/buzoBosqueFlashAdelante_dakvgd.jpg",
  },
  {
    id: 7,
    title: "Buzo The End",
    price: 16000,
    stock: 5,
    description: "Oversize",
    category: "Buzo",
    img: "https://res.cloudinary.com/dfcnmxndf/image/upload/v1686949762/buzoLilaFlash_ogfbvj.jpg",
  },
];
